#pragma once

#define __BOARD_VECTOR_HANDLERS__ __STM32F407_VECTOR_HANDLERS__

#define __STM32F407_VECTOR_HANDLERS__ X(Window_Watchdog_IRQHandler) \
    X(PVD_IRQHandler) \
    X(TAMPER_STAMP_IRQHandler) \
    X(RTC_WKUP_IRQHandler) \
    X(FLASH_IRQHandler) \
    X(RCC_IRQHandler) \
    X(EXTI0_IRQHandler) \
    X(EXTI1_IRQHandler) \
    X(EXTI2_IRQHandler) \
    X(EXTI3_IRQHandler) \
    X(EXTI4_IRQHandler) \
    X(DMA1_Stream0_IRQHandler) \
    X(DMA1_Stream1_IRQHandler) \
    X(DMA1_Stream2_IRQHandler) \
    X(DMA1_Stream3_IRQHandler) \
    X(DMA1_Stream4_IRQHandler) \
    X(DMA1_Stream5_IRQHandler) \
    X(DMA1_Stream6_IRQHandler) \
    X(ADC_IRQHandler) \
    X(CAN1_TX_IRQHandler) \
    X(CAN1_RX0_IRQHandler) \
    X(CAN1_RX1_IRQHandler) \
    X(CAN1_SCE_IRQHandler) \
    X(EXTI9_5_IRQHandler) \
    X(TIM1_BRK_TIM9_IRQHandler) \
    X(TIM1_UP_TIM10_IRQHandler) \
    X(TIM1_TRG_COM_TIM11_IRQHandler) \
    X(TIM1_CC_IRQHandler) \
    X(TIM2_IRQHandler) \
    X(TIM3_IRQHandler) \
    X(TIM4_IRQHandler) \
    X(I2C1_EV_IRQHandler) \
    X(I2C1_ER_IRQHandler) \
    X(I2C2_EV_IRQHandler) \
    X(I2C2_ER_IRQHandler) \
    X(SPI1_IRQHandler) \
    X(SPI2_IRQHandler) \
    X(USART1_IRQHandler) \
    X(USART2_IRQHandler) \
    X(USART3_IRQHandler) \
    X(EXTI15_10_IRQHandler) \
    X(RTC_Alarm_IRQHandler) \
    X(OTG_FS_WKUP_IRQHandler) \
    X(TIM8_BRK_TIM12_IRQHandler) \
    X(TIM8_UP_TIM13_IRQHandler) \
    X(TIM8_TRG_COM_TIM14_IRQHandler) \
    X(TIM8_CC_IRQHandler) \
    X(DMA1_Stream7_IRQHandler) \
    X(FSMC_IRQHandler) \
    X(SDIO_IRQHandler) \
    X(TIM5_IRQHandler) \
    X(SPI3_IRQHandler) \
    X(UART4_IRQHandler) \
    X(UART5_IRQHandler) \
    X(TIM6_DAC_IRQHandler) \
    X(TIM7_IRQHandler) \
    X(DMA2_Stream0_IRQHandler) \
    X(DMA2_Stream1_IRQHandler) \
    X(DMA2_Stream2_IRQHandler) \
    X(DMA2_Stream3_IRQHandler) \
    X(DMA2_Stream4_IRQHandler) \
    X(ETH_IRQHandler) \
    X(ETH_WKUP_IRQHandler) \
    X(CAN2_TX_IRQHandler) \
    X(CAN2_RX0_IRQHandler) \
    X(CAN2_RX1_IRQHandler) \
    X(CAN2_SCE_IRQHandler) \
    X(OTG_FS_IRQHandler) \
    X(DMA2_Stream5_IRQHandler) \
    X(DMA2_Stream6_IRQHandler) \
    X(DMA2_Stream7_IRQHandler) \
    X(USART6_IRQHandler) \
    X(I2C3_EV_IRQHandler) \
    X(I2C3_ER_IRQHandler) \
    X(OTG_HS_EP1_OUT_IRQHandler) \
    X(OTG_HS_EP1_IN_IRQHandler) \
    X(OTG_HS_WKUP_IRQHandler) \
    X(OTG_HS_IRQHandler) \
    X(DCMI_IRQHandler) \
    X(CRYP_IRQHandler) \
    X(HASH_RNG_IRQHandler) \
    X(FPU_IRQHandler) \



